### PR TITLE
Add Cloud Spanner: Read Statistics blog link

### PR DESCRIPTION
**Pull request by mayurkale22**

### CODE REVIEW

**Comment by mayurkale22** [comment]
@lgruen Please review and merge, thank you :)

**Comment by mayurkale22** [comment]
@lgruen Please review when you have a moment.

**Comment by sserban-us** [comment]
@mayurkale22 we now have a dedicated page for blogs (see blog.md). Please add the link there, and feel free to add links to the blog posts about other statistics (transactions, running queries) too.

**Comment by mayurkale22** [comment]
> @mayurkale22 we now have a dedicated page for blogs (see blog.md). Please add the link there, and feel free to add links to the blog posts about other statistics (transactions, running queries) too.

Ok cool. Closing this one.

**Pull request closed without merging**
